# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class DemoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ApiCreate = channel.unary_unary(
        '/demo.DemoService/ApiCreate',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.ApiUpdate = channel.unary_unary(
        '/demo.DemoService/ApiUpdate',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.ApiList = channel.unary_unary(
        '/demo.DemoService/ApiList',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.ApiDelete = channel.unary_unary(
        '/demo.DemoService/ApiDelete',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )


class DemoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ApiCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApiUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApiList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApiDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ApiCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ApiCreate,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'ApiUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.ApiUpdate,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'ApiList': grpc.unary_unary_rpc_method_handler(
          servicer.ApiList,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'ApiDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ApiDelete,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.DemoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
